# Generated by Django 3.2 on 2022-03-26 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0003_auto_20220325_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='notes',
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_notes',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reservations', to=settings.AUTH_USER_MODEL),
        ),
    ]
